### ISSUE TITLE
Crash when running without connected headset

### ISSUE THREAD

**Issue by DanielQuick** [awtterpip/bevy_oxr#27]
Tested using Windows 11. Start any bevy_openxr app without a headset connected.

```
thread 'main' panicked at C:\Users\Daniel\.cargo\git\checkouts\bevy_openxr-1dedcf84dfa11c13\f168a40\src\lib.rs:81:62:
called `Result::unwrap()` on an `Err` value: the specified form factor is supported, but the device is currently not available, e.g. not plugged in or powered off
stack backtrace:
   0:     0x7ffe6567738a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
   1:     0x7ffe656abb5b - core::fmt::write::h8a7f6edbcadee319
   2:     0x7ffe6566cc51 - <std::io::IoSlice as core::fmt::Debug>::fmt::h0ee392ef0f96e369
   3:     0x7ffe6567710a - std::sys_common::backtrace::lock::h134eeaadb35136bd
   4:     0x7ffe6567a8ca - std::panicking::default_hook::h81d7caaa8c7a40b4
   5:     0x7ffe6567a538 - std::panicking::default_hook::h81d7caaa8c7a40b4
   6:     0x7ffe6567b03e - std::panicking::rust_panic_with_hook::h8ac326f3b5470b08
   7:     0x7ffe6567af2d - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h353ca2f9698f73b3
   8:     0x7ffe65678049 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
   9:     0x7ffe6567ac30 - rust_begin_unwind
  10:     0x7ffe656e0d85 - core::panicking::panic_fmt::hb3ce2a19a4187054
  11:     0x7ffe656e12e4 - core::result::unwrap_failed::h014e7fe1f263d3f8
  12:     0x7ff6170e9ed5 - enum2$<core::result::Result<tuple$<bevy_render::renderer::render_device::RenderDevice,bevy_render::renderer::RenderQueue,bevy_render::renderer::RenderAdapterInfo,bevy_render::renderer::RenderAdapter,wgpu::Instance,bevy_openxr::resources::XrInstance,bevy_o
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\result.rs:1077
  13:     0x7ff6170e9ed5 - bevy_openxr::impl$0::build
                               at C:\Users\Daniel\.cargo\git\checkouts\bevy_openxr-1dedcf84dfa11c13\f168a40\src\lib.rs:81
  14:     0x7ffe51a9c5bc - bevy_app::app::App::add_boxed_plugin
                               at C:\Users\Daniel\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.12.0\src\app.rs:638
  15:     0x7ffe51a97bce - bevy_app::plugin_group::PluginGroupBuilder::finish
                               at C:\Users\Daniel\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.12.0\src\plugin_group.rs:182
  16:     0x7ff6170d2377 - open_xr_test::main
                               at C:\Users\Daniel\documents\projects\open_xr_test\src\main.rs:5
  17:     0x7ff6170c8396 - core::ops::function::FnOnce::call_once
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  18:     0x7ff6170c8396 - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\sys_common\backtrace.rs:154
  19:     0x7ff6170bfb2c - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\rt.rs:166
  20:     0x7ffe6565caf8 - std::rt::lang_start_internal::h8a2184178aa988dc
  21:     0x7ff6170d409c - main
  22:     0x7ff61729cab0 - invoke_main
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23:     0x7ff61729cab0 - __scrt_common_main_seh
                               at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24:     0x7ffee301257d - BaseThreadInitThunk
  25:     0x7ffee3b2aa78 - RtlUserThreadStart
```

**Comment by Schmarni-Dev** [comment]
Should be fixed
