### ISSUE TITLE
stack backtrace not availabe on windows when loading plugin

### ISSUE THREAD

**Issue by maprohu** [awtterpip/bevy_oxr#63]
Hi!

First of all, awesome job on this plugin, I am really excited about it! :)

I noticed that when I use this plugin, I get no (useful) stacktrace when something panics.

 Here is the code:

```rust
use bevy::prelude::*;
use bevy_oxr::DefaultXrPlugins;

fn main() {
    App::new().add_systems(Update, || {
        panic!("x");
    }).add_plugins(DefaultXrPlugins::default()).run();
}
```

Here is the result:

```
C:/Users/mapro/.cargo/bin/cargo.exe run --color=always --example oxr_panic --manifest-path C:\Users\mapro\development\private\rust\bevy\sandbox\Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target\debug\examples\oxr_panic.exe`
2024-01-14T19:27:04.743712Z  INFO bevy_winit::system: Creating new window "Ambient" (0v0)
2024-01-14T19:27:04.945358Z  INFO bevy_oxr::graphics::vulkan: available xr exts: XrExtensions(
    ExtensionSet {
        almalence_digital_lens_control: false,
        bd_controller_interaction: false,
        epic_view_configuration_fov: false,
        ext_performance_settings: false,
        ext_thermal_query: false,
        ext_debug_utils: true,
        ext_eye_gaze_interaction: false,
        ext_view_configuration_depth_range: false,
        ext_conformance_automation: false,
        ext_hand_tracking: true,
        ext_win32_appcontainer_compatible: true,
        ext_dpad_binding: false,
        ext_hand_joints_motion_range: false,
        ext_samsung_odyssey_controller: false,
        ext_hp_mixed_reality_controller: false,
        ext_palm_pose: true,
        ext_uuid: false,
        ext_hand_interaction: false,
        ext_active_action_set_priority: true,
        ext_local_floor: true,
        ext_hand_tracking_data_source: false,
        ext_plane_detection: false,
        fb_composition_layer_image_layout: false,
        fb_composition_layer_alpha_blend: false,
        fb_swapchain_update_state: false,
        fb_composition_layer_secure_content: false,
        fb_body_tracking: true,
        fb_display_refresh_rate: true,
        fb_color_space: true,
        fb_hand_tracking_mesh: true,
        fb_hand_tracking_aim: true,
        fb_hand_tracking_capsules: true,
        fb_spatial_entity: true,
        fb_foveation: false,
        fb_foveation_configuration: false,
        fb_keyboard_tracking: true,
        fb_triangle_mesh: true,
        fb_passthrough: true,
        fb_render_model: true,
        fb_spatial_entity_query: true,
        fb_spatial_entity_storage: true,
        fb_foveation_vulkan: false,
        fb_swapchain_update_state_opengl_es: false,
        fb_swapchain_update_state_vulkan: false,
        fb_touch_controller_pro: true,
        fb_spatial_entity_sharing: true,
        fb_space_warp: false,
        fb_haptic_amplitude_envelope: true,
        fb_scene: true,
        fb_scene_capture: false,
        fb_spatial_entity_container: true,
        fb_face_tracking: true,
        fb_eye_tracking_social: true,
        fb_passthrough_keyboard_hands: false,
        fb_composition_layer_settings: false,
        fb_touch_controller_proximity: true,
        fb_haptic_pcm: true,
        fb_composition_layer_depth_test: false,
        fb_spatial_entity_storage_batch: true,
        fb_spatial_entity_user: true,
        htc_vive_cosmos_controller_interaction: false,
        htc_facial_tracking: false,
        htc_vive_focus3_controller_interaction: false,
        htc_hand_interaction: false,
        htc_vive_wrist_tracker_interaction: false,
        htc_passthrough: false,
        htc_foveation: false,
        huawei_controller_interaction: false,
        khr_composition_layer_cube: true,
        khr_composition_layer_depth: true,
        khr_vulkan_swapchain_format_list: false,
        khr_composition_layer_cylinder: true,
        khr_composition_layer_equirect: true,
        khr_opengl_enable: true,
        khr_opengl_es_enable: false,
        khr_vulkan_enable: true,
        khr_d3d11_enable: true,
        khr_d3d12_enable: true,
        khr_visibility_mask: true,
        khr_composition_layer_color_scale_bias: true,
        khr_win32_convert_performance_counter_time: true,
        khr_convert_timespec_time: true,
        khr_loader_init: false,
        khr_vulkan_enable2: true,
        khr_composition_layer_equirect2: false,
        khr_binding_modification: false,
        khr_swapchain_usage_input_attachment_bit: false,
        meta_foveation_eye_tracked: false,
        meta_local_dimming: false,
        meta_passthrough_preferences: true,
        meta_virtual_keyboard: true,
        meta_vulkan_swapchain_create_info: false,
        meta_performance_metrics: true,
        meta_headset_id: true,
        meta_passthrough_color_lut: true,
        ml_ml2_controller_interaction: false,
        ml_frame_end_info: false,
        ml_global_dimmer: false,
        ml_compat: false,
        ml_user_calibration: false,
        mnd_headless: false,
        mnd_swapchain_usage_input_attachment_bit: false,
        msft_unbounded_reference_space: false,
        msft_spatial_anchor: false,
        msft_spatial_graph_bridge: false,
        msft_hand_interaction: false,
        msft_hand_tracking_mesh: false,
        msft_secondary_view_configuration: false,
        msft_first_person_observer: false,
        msft_controller_model: false,
        msft_perception_anchor_interop: false,
        msft_holographic_window_attachment: false,
        msft_composition_layer_reprojection: false,
        msft_spatial_anchor_persistence: false,
        oculus_audio_device_guid: true,
        oculus_external_camera: true,
        oppo_controller_interaction: false,
        qcom_tracking_optimization_settings: false,
        ultraleap_hand_tracking_forearm: false,
        valve_analog_threshold: false,
        varjo_quad_views: false,
        varjo_foveated_rendering: false,
        varjo_composition_layer_depth_test: false,
        varjo_environment_depth_estimation: false,
        varjo_marker_tracking: false,
        varjo_view_offset: false,
        yvr_controller_interaction: false,
        other: [
            "XR_OCULUS_recenter_event\0",
            "XR_OCULUS_ovrsession_handle\0",
            "XR_METAX1_simultaneous_hands_controllers_management\0",
            "XR_META_body_tracking_full_body\0",
            "XR_META_body_tracking_fidelity\0",
            "XR_META_body_tracking_calibration\0",
            "XR_FB_face_tracking2\0",
            "XR_METAX1_passthrough_color_lut\0",
            "XR_META_spatial_entity_mesh\0",
            "XR_META_environment_depth\0",
            "XR_META_touch_controller_plus\0",
            "XR_FBX1_touch_controller_extras\0",
            "XR_METAX2_detached_controllers\0",
        ],
    },
)
2024-01-14T19:27:04.947566Z  INFO bevy_oxr::graphics::vulkan: available xr layers: []
2024-01-14T19:27:04.951489Z  INFO bevy_oxr::graphics::vulkan: created instance
2024-01-14T19:27:04.955417Z  INFO bevy_oxr::graphics::vulkan: created system
2024-01-14T19:27:04.955637Z  INFO bevy_oxr::graphics::vulkan: loaded OpenXR runtime: Oculus 1.92.0 Oculus Quest2
2024-01-14T19:27:05.006322Z  INFO bevy_oxr::graphics::vulkan: creating vulkan instance with these extensions: [
    "VK_KHR_surface",
    "VK_KHR_win32_surface",
    "VK_EXT_swapchain_colorspace",
    "VK_KHR_get_physical_device_properties2",
]
2024-01-14T19:27:05.043329Z  INFO bevy_oxr::graphics::vulkan: created vulkan instance
2024-01-14T19:27:06.059289Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: Limits::max_storage_textures_per_shader_stage is less than 5.
2024-01-14T19:27:06.187551Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "22631", cpu: "12th Gen Intel(R) Core(TM) i7-12700H", core_count: "14", memory: "31.7 GiB" }
2024-01-14T19:27:06.199509Z  INFO bevy_oxr: entered XR state IDLE
2024-01-14T19:27:06.199665Z  INFO bevy_oxr: entered XR state READY
[BodyApiPlugin][INFO]: BeginSession called for BodyApi Plugin
[BodyApiPlugin][INFO]: BeginSession called for BodyApi Plugin
[BodyApiPlugin][INFO]: BeginSession called for BodyApi Plugin
[BodyApiPlugin][INFO]: BeginSession called for BodyApi Plugin
2024-01-14T19:27:06.200392Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
thread 'Compute Task Pool (6)' panicked at sandbox\examples\oxr_panic.rs:6:9:
x
stack backtrace:
   0:     0x7ff7d087cca3 - <unknown>
   1:     0x7ff7d089792d - <unknown>
   2:     0x7ff7d08791f1 - <unknown>
   3:     0x7ff7d087caaa - <unknown>
   4:     0x7ff7d087ed99 - <unknown>
   5:     0x7ff7d087ea5b - <unknown>
   6:     0x7ff7d087f284 - <unknown>
   7:     0x7ff7d087f11b - <unknown>
   8:     0x7ff7d087d339 - <unknown>
   9:     0x7ff7d087ee64 - <unknown>
  10:     0x7ff7d08ed8d7 - <unknown>
  11:     0x7ff7cd0b1376 - <unknown>
  12:     0x7ff7cd0b1191 - <unknown>
  13:     0x7ff7cd0b1e2f - <unknown>
  14:     0x7ff7cd0b116e - <unknown>
  15:     0x7ff7cd0b1fa9 - <unknown>
  16:     0x7ff7d0618a88 - <unknown>
  17:     0x7ff7d05949b7 - <unknown>
  18:     0x7ff7d062b7d8 - <unknown>
  19:     0x7ff7d05c546c - <unknown>
  20:     0x7ff7d05cd723 - <unknown>
  21:     0x7ff7d05c4541 - <unknown>
  22:     0x7ff7d05cf529 - <unknown>
  23:     0x7ff7d061852d - <unknown>
  24:     0x7ff7d062b2ea - <unknown>
  25:     0x7ff7d05c263a - <unknown>
  26:     0x7ff7d062b8e3 - <unknown>
  27:     0x7ff7d05c5406 - <unknown>
  28:     0x7ff7d05cd723 - <unknown>
  29:     0x7ff7d05c435b - <unknown>
  30:     0x7ff7d05cf44b - <unknown>
  31:     0x7ff7d05c1fef - <unknown>
  32:     0x7ff7d05dc702 - <unknown>
  33:     0x7ff7d061fb21 - <unknown>
  34:     0x7ff7d05940fa - <unknown>
  35:     0x7ff7d062b90b - <unknown>
  36:     0x7ff7d05c50ae - <unknown>
  37:     0x7ff7d05cd723 - <unknown>
  38:     0x7ff7d05c4424 - <unknown>
  39:     0x7ff7d05cf3eb - <unknown>
  40:     0x7ff7d061d04e - <unknown>
  41:     0x7ff7d069b0be - <unknown>
  42:     0x7ff7d068dc8c - <unknown>
  43:     0x7ff7d0689445 - <unknown>
  44:     0x7ff7d068d7f9 - <unknown>
  45:     0x7ff7d0686f58 - <unknown>
  46:     0x7ff7d068f443 - <unknown>
  47:     0x7ff7d068f203 - <unknown>
  48:     0x7ff7d0686df2 - <unknown>
  49:     0x7ff7d0685b2c - <unknown>
  50:     0x7ff7d0687fb1 - <unknown>
  51:     0x7ff7d0689913 - <unknown>
  52:     0x7ff7d0687cab - <unknown>
  53:     0x7ff7d0680781 - <unknown>
  54:     0x7ff7d0685875 - <unknown>
  55:     0x7ff7d068f31a - <unknown>
  56:     0x7ff7d068f14e - <unknown>
  57:     0x7ff7d06856c8 - <unknown>
  58:     0x7ff7d0680769 - <unknown>
  59:     0x7ff7d06816a1 - <unknown>
  60:     0x7ff7d0686bd1 - <unknown>
  61:     0x7ff7d068807b - <unknown>
  62:     0x7ff7d0689913 - <unknown>
  63:     0x7ff7d0687d64 - <unknown>
  64:     0x7ff7d06814cb - <unknown>
  65:     0x7ff7d067d59e - <unknown>
  66:     0x7ff7d0884b8c - <unknown>
  67:     0x7ff8b63c257d - <unknown>
  68:     0x7ff8b862aa58 - <unknown>
Encountered a panic in system `oxr_panic::main::{{closure}}`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

As you see the there are no line numbers or any other info in the stack trace.

`Cargo.toml`:
```toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
bevy_oxr = { git = "https://github.com/awtterpip/bevy_oxr" }
```

I do get a proper stack trace when I do not load the plugin:

```rust
use bevy::prelude::*;

fn main() {
    App::new().add_systems(Update, || {
        panic!("x");
    }).run();
}
```

Output:
```
C:/Users/mapro/.cargo/bin/cargo.exe run --color=always --example without_oxr --manifest-path C:\Users\mapro\development\private\rust\bevy\sandbox\Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target\debug\examples\without_oxr.exe`
thread 'TaskPool (16)' panicked at sandbox\examples\without_oxr.rs:5:9:
x
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\core\src\panicking.rs:72
   2: without_oxr::main::closure$0
             at .\sandbox\examples\without_oxr.rs:5
   3: core::ops::function::impls::impl$3::call_mut<tuple$<>,without_oxr::main::closure_env$0>
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\ops\function.rs:294
   4: bevy_ecs::system::function_system::impl$9::run::call_inner<tuple$<>,ref_mut$<without_oxr::main::closure_env$0> >
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\system\function_system.rs:642
   5: bevy_ecs::system::function_system::impl$9::run<tuple$<>,without_oxr::main::closure_env$0>
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\system\function_system.rs:645
   6: bevy_ecs::system::function_system::impl$6::run_unsafe<void (*)(),without_oxr::main::closure_env$0>
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\system\function_system.rs:485
   7: bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure$0
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\schedule\executor\multi_threaded.rs:505
   8: core::ops::function::FnOnce::call_once<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure_env$0,tuple$<> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\ops\function.rs:250
   9: core::panic::unwind_safe::impl$23::call_once<tuple$<>,bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure_env$0>
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\panic\unwind_safe.rs:272
  10: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure_env$0>,tuple$<> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:552
  11: bevy_ecs::schedule::set::impl$28::eq
  12: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure_env$0> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:516
  13: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0::closure_env$0>,tuple$<> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panic.rs:142
  14: bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block$0
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\schedule\executor\multi_threaded.rs:500
  15: core::panic::unwind_safe::impl$26::poll<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block_env$0> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\panic\unwind_safe.rs:297
  16: futures_lite::future::impl$14::poll::closure$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block_env$0> > >
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  17: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\panic\unwind_safe.rs:272
  18: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_blo
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:552
  19: bevy_ecs::schedule::set::impl$28::eq
  20: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::im
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:516
  21: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block_e
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panic.rs:142
  22: futures_lite::future::impl$14::poll<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system_task::async_block_env$0> > >
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  23: async_executor::impl$5::spawn::async_block$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.8.0\src\lib.rs:158
  24: async_task::raw::impl$3::run::closure$1<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\raw.rs:550
  25: core::ops::function::FnOnce::call_once<async_task::raw::impl$3::run::closure_env$1<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global>
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\ops\function.rs:250
  26: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > > > >,async_task::raw::impl$3::run::closure_env$1<enum2$<asyn
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\panic\unwind_safe.rs:272
  27: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::impl$3::run::closure_env$1<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::ma
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:552
  28: bevy_ecs::schedule::set::impl$28::eq
  29: std::panicking::try<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > > > >,core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::impl$3::run::closure
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:516
  30: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::impl$3::run::closure_env$1<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panic.rs:142
  31: async_task::raw::RawTask<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::panic::unwind
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\raw.rs:549
  32: async_task::runnable::Runnable<tuple$<> >::run<tuple$<> >
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:781
  33: async_executor::impl$5::run::async_fn$0::async_block$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_en
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.8.0\src\lib.rs:254
  34: futures_lite::future::impl$7::poll<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_channel::
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-2.2.0\src\future.rs:449
  35: async_executor::impl$5::run::async_fn$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_chan
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.8.0\src\lib.rs:261
  36: futures_lite::future::block_on::closure$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,enum2$<async_executor::impl$5::run::async_fn_env$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
  37: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum2$<core::result::Result<
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\thread\local.rs:270
  38: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum2$<core::result::Result<tupl
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\thread\local.rs:246
  39: futures_lite::future::block_on<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,enum2$<async_executor::impl$5::run::async_fn_env$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks:
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  40: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.12.1\src\task_pool.rs:180
  41: std::panicking::try::do_call<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure_env$0,enum2$<core::result::Result<tuple$<>,async_channel::RecvError> > >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:552
  42: bevy_tasks::thread_executor::ThreadExecutorTicker::tick
  43: std::panicking::try<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure_env$0>
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panicking.rs:516
  44: std::panic::catch_unwind<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure_env$0,enum2$<core::result::Result<tuple$<>,async_channel::RecvError> > >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\panic.rs:142
  45: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.12.1\src\task_pool.rs:174
  46: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with<async_executor::LocalExecutor,bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure_env$0,tuple$<> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\thread\local.rs:270
  47: std::thread::local::LocalKey<async_executor::LocalExecutor>::with<async_executor::LocalExecutor,bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure_env$0,tuple$<> >
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\thread\local.rs:246
  48: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at C:\Users\mapro\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.12.1\src\task_pool.rs:167
  49: core::hint::black_box
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\hint.rs:286
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `without_oxr::main::{{closure}}`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `target\debug\examples\without_oxr.exe` (exit code: 101)

Process finished with exit code 101
```

**Comment by Schmarni-Dev** [comment]
Does this still happen after the rewrite? If so please reopen
